# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/BC_Final_Project/hdl/projects/FIR_Filter_Design/FIR_Filter_Design.srcs/sources_1/bd/FIR_design_1/ip/FIR_design_1_Sine_wave_3o5MHz_0/FIR_design_1_Sine_wave_3o5MHz_0.xci
# IP: The module: 'FIR_design_1_Sine_wave_3o5MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/BC_Final_Project/hdl/projects/FIR_Filter_Design/FIR_Filter_Design.gen/sources_1/bd/FIR_design_1/ip/FIR_design_1_Sine_wave_3o5MHz_0/FIR_design_1_Sine_wave_3o5MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_design_1_Sine_wave_3o5MHz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/BC_Final_Project/hdl/projects/FIR_Filter_Design/FIR_Filter_Design.srcs/sources_1/bd/FIR_design_1/ip/FIR_design_1_Sine_wave_3o5MHz_0/FIR_design_1_Sine_wave_3o5MHz_0.xci
# IP: The module: 'FIR_design_1_Sine_wave_3o5MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/BC_Final_Project/hdl/projects/FIR_Filter_Design/FIR_Filter_Design.gen/sources_1/bd/FIR_design_1/ip/FIR_design_1_Sine_wave_3o5MHz_0/FIR_design_1_Sine_wave_3o5MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_design_1_Sine_wave_3o5MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
